name: Push to Registry

on:
  workflow_dispatch:
    inputs:
      version:
        description: "The version of the release"
        required: true
        default: "0.0.0"

jobs:
  registry:
    uses: labdigital-main/terraform-github-workflows/.github/workflows/terraform-module-release-v2.yaml@main
    secrets: inherit
    with:
      module-version: ${{ github.event.inputs.version }}
      jfrog-repo: aws
      jfrog-url: https://labdigital.jfrog.io
