name: Module Release

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write
  actions: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Prepare release
        uses: labd/changie-release-action@v0.3.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
